name: ci
on:
  push:
    branches:
      - 1.x-maintenance
      - master
  pull_request:
    branches:
      - 1.x-maintenance
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        gemfile:
          - Gemfile
          - spec/support/Gemfile.rails6.1
          - spec/support/Gemfile.rails7.0
          - spec/support/Gemfile.rails7.1
          - spec/support/Gemfile.rails7.2
          - spec/support/Gemfile.rails8.0
        exclude:
          - ruby: '3.1'
            gemfile: 'Gemfile.rails8'
        bundler:
          - "2"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler }}
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
