name: ci
on:
  push:
    branches:
      - 1.x-maintenance
      - master
  pull_request:
    branches:
      - 1.x-maintenance
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', '3.3', '3.4']
        rails: ['6.1', '7.0', '7.1', '7.2', '8.0']
        gemfile: ['spec/support/Gemfile.rails{{ matrix.rails }}']
        exclude:
          - ruby: '3.1'
            rails: '8.0'
          - ruby: '3.4'
            rails: '6.1'
          - ruby: '3.4'
            rails: '7.0'
        bundler:
          - "2"
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler }}
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install --gemfile=${{ matrix.gemfile }}
      - name: Run tests
        run: bundle exec rspec
