name: ci
on:
  push:
    branches:
      - 1.x-maintenance
      - master
  pull_request:
    branches:
      - 1.x-maintenance
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2', '3.3', '3.4']
        rails: ['7.2']
        gemfile:
          - Gemfile
          - Gemfile.rails7.2
        bundler:
          - "2"
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: ${{ matrix.bundler }}
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install dependencies
        run: bundle install --gemfile=${{ matrix.gemfile }}
      - name: Run tests
        run: bundle exec rspec
